
#ifndef DGD_AXI_DMA_
#define DGD_AXI_DMA_

#define DRIVER_NAME "dgd-axi-dma"

#define IOCTL_DGD_AXI_DMA_MAGIC						'r'
#define IOCTL_DGD_AXI_DMA_TRANSFER_BLOCK_SIZE		_IOW( IOCTL_DGD_AXI_DMA_MAGIC,  0, int )
#define IOCTL_DGD_AXI_DMA_ALLOCATE_BUFFERS			_IOW( IOCTL_DGD_AXI_DMA_MAGIC,  1, int )
#define IOCTL_DGD_AXI_DMA_SET_BLOCKS_COUNT_MM2S		_IOW( IOCTL_DGD_AXI_DMA_MAGIC,  2, int )
#define IOCTL_DGD_AXI_DMA_SET_BLOCKS_COUNT_S2MM		_IOW( IOCTL_DGD_AXI_DMA_MAGIC,  3, int )
#define IOCTL_DGD_AXI_DMA_START_S2MM				_IOW( IOCTL_DGD_AXI_DMA_MAGIC,  4, int )
#define IOCTL_DGD_AXI_DMA_START_MM2S				_IOW( IOCTL_DGD_AXI_DMA_MAGIC,  5, int )
#define IOCTL_DGD_AXI_DMA_IDX_S2MM					_IOR( IOCTL_DGD_AXI_DMA_MAGIC,  6, int )
#define IOCTL_DGD_AXI_DMA_IDX_MM2S					_IOR( IOCTL_DGD_AXI_DMA_MAGIC,  7, int )
#define IOCTL_DGD_AXI_DMA_MMAP_S2MM					_IOW( IOCTL_DGD_AXI_DMA_MAGIC,  8, int )
#define IOCTL_DGD_AXI_DMA_MMAP_MM2S					_IOW( IOCTL_DGD_AXI_DMA_MAGIC,  9, int )
#define IOCTL_DGD_AXI_DMA_MMAP_BUFFER_IDX			_IOW( IOCTL_DGD_AXI_DMA_MAGIC, 10, int )
#define IOCTL_DGD_AXI_DMA_FREE_BUFFERS 				_IOW( IOCTL_DGD_AXI_DMA_MAGIC, 11, int )
#define IOCTL_DGD_AXI_DMA_LOG						_IOW( IOCTL_DGD_AXI_DMA_MAGIC, 12, int )
#define IOCTL_DGD_AXI_BUFFERS_COUNT_MM2S			_IOW( IOCTL_DGD_AXI_DMA_MAGIC, 13, int )
#define IOCTL_DGD_AXI_BUFFERS_COUNT_S2MM			_IOW( IOCTL_DGD_AXI_DMA_MAGIC, 14, int )
#define IOCTL_DGD_AXI_DMA_DUMP_REGS					_IOW( IOCTL_DGD_AXI_DMA_MAGIC, 15, int )
#define IOCTL_DGD_AXI_DMA_RESET						_IOW( IOCTL_DGD_AXI_DMA_MAGIC, 16, int )
#define IOCTL_DGD_AXI_DMA_STATUS_S2MM				_IOW( IOCTL_DGD_AXI_DMA_MAGIC, 17, int )
#define IOCTL_DGD_AXI_DMA_STATUS_MM2S				_IOW( IOCTL_DGD_AXI_DMA_MAGIC, 18, int )
#define IOCTL_DGD_AXI_DMA_GET_BLOCKS_COUNT_MM2S		_IOW( IOCTL_DGD_AXI_DMA_MAGIC, 19, int )
#define IOCTL_DGD_AXI_DMA_GET_BLOCKS_COUNT_S2MM		_IOW( IOCTL_DGD_AXI_DMA_MAGIC, 20, int )



#define DGD_AXI_DMA_STATUS_HALTED               0x00000001
#define DGD_AXI_DMA_STATUS_IDLE                 0x00000002
#define DGD_AXI_DMA_STATUS_SG_INCLDED           0x00000008
#define DGD_AXI_DMA_STATUS_DMA_INTERNAL_ERR     0x00000010
#define DGD_AXI_DMA_STATUS_DMA_SLAVE_ERR        0x00000020
#define DGD_AXI_DMA_STATUS_DMA_DECODE_ERR       0x00000040
#define DGD_AXI_DMA_STATUS_SG_INTERNAL_ERR      0x00000100
#define DGD_AXI_DMA_STATUS_SG_SLAVE_ERR         0x00000200
#define DGD_AXI_DMA_STATUS_SG_DECODE_ERR        0x00000400
#define DGD_AXI_DMA_STATUS_IOC_IRQ              0x00001000
#define DGD_AXI_DMA_STATUS_DELAY_IRQ            0x00002000
#define DGD_AXI_DMA_STATUS_ERR_IRQ              0x00004000

#endif
